name: sonarqube-code-quality
on: 
  pull_request:
    branches:
      - "main"

jobs:
  sonarqube-code-coverage:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Go Coverage test 
        run: go test -coverprofile=coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  docker-build-and-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    steps:      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false # We just push to code on CD process
          tags: wesleywillians/fc2.0-ci-go:latest



 